Remove core dependency and change build system

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,19 +4,32 @@ clear
 
 if [ "$1" == "build" ]; then 
 
-	# First, clean up
+	# First, setup Oasis
+	oasis setup || exit
+
+	# Then, clean up
 	make clean distclean || exit
 	clear
 
-	# Then, setup Oasis
-	oasis setup || exit
-
 	# Afterwards, add stuff to the files
 	if grep -q 'mark_tag_used("tests")' myocamlbuild.ml; then
-		: # Again, do nothing
+		: # Do nothing
 	else
 		echo "" >> myocamlbuild.ml
 		echo 'mark_tag_used("tests")' >> myocamlbuild.ml
+	fi
+
+	if grep -q '# _TAGS ADDED' _tags; then
+		: # Again, do nothing
+	else
+		echo "" >> _tags; echo "" >> _tags
+		echo "# _TAGS ADDED" >> _tags
+
+		# Disable -41 for Menhir
+		echo "<src/parser.*>: warn(+A-4-6-9-40..42-44), warn_error(+1..49), strict_sequence, safe_string" >> _tags
+		# Otherwise, keep our defined default
+		echo "<src/*.ml{,i}>: warn(+A-4-6-9-40-42-44), warn_error(+1..49), strict_sequence, safe_string" >> _tags
+		echo '' >> _tags
 	fi
 
 	./configure || exit
